# .github/labeler.yml

# Apply a label for changes to the documentation
documentation:
  - 'docs/**/*'
  - '*.md'

# Apply a label for changes to the core NestJS application code
core:
  - 'src/app.module.ts'
  - 'src/main.ts'
  
modules:
  - 'src/**/*.module.ts'

# Apply a label for changes to the DTOs (Data Transfer Objects)
dtos:
  - 'src/**/dto/*.dto.ts'

# Apply a label for changes to the configuration files
configuration:
  - '.github/**/*'
  - 'config/**/*'
  - '*.yml'
  - '*.yaml'

# Apply a label for changes to the tests
tests:
  - 'test/**/*'
  - 'src/**/*.spec.ts'

# Apply a label for changes to the CI/CD workflows
ci-cd:
  - '.github/workflows/**/*'

# Apply a label for changes to the database scripts
database:
  - 'src/db/**/*'
  - 'migrations/**/*'
  - 'seeders/**/*'