# .github/labeler.yml

# Apply a label for changes to the documentation
Documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '*.md'

# Apply a label for changes to the core NestJS application code
Core:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/app.module.ts'
      - 'src/main.ts'

# Apply a label for changes to the modules
Modules:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*.module.ts'

# Apply a label for changes to the DTOs (Data Transfer Objects)
DTOs:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/dto/*.dto.ts'

# Apply a label for changes to the configuration files
Configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'config/**/*'
      - '*.yml'
      - '*.yaml'

# Apply a label for changes to the tests
Tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'test/**/*'
      - 'src/**/*.spec.ts'

# Apply a label for changes to the CI/CD workflows
CI-CD:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'

# Apply a label for changes to the database scripts
Database:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/db/**/*'
      - 'migrations/**/*'
      - 'seeders/**/*'
