name: 'Dependency review'
on:
  push:
    branches: [ "develop", "staging", "production" ]
  pull_request:
    branches: [ "develop", "staging", "production" ]
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 06:00 AM IST (12:30 AM UTC)

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        
      - name: 'Set Base and Head Refs for Push Events'
        if: github.event_name == 'push'
        run: |
          echo "BASE_REF=$(git rev-parse origin/${{ github.event.repository.default_branch }})" >> $GITHUB_ENV
          echo "HEAD_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base_ref: ${{ env.BASE_REF }}
          head_ref: ${{ env.HEAD_REF }}
          comment-summary-in-pr: always
          fail-on-severity: moderate
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
          retry-on-snapshot-warnings: true
