name: PR Badge

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Determine PR type
      id: determine-pr-type
      run: |
        PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')
        if [[ "$PR_TITLE" == *"feature"* ]]; then
          echo "::set-output name=type::feature"
        elif [[ "$PR_TITLE" == *"patch"* ]]; then
          echo "::set-output name=type::patch"
        elif [[ "$PR_TITLE" == *"bugfix"* ]]; then
          echo "::set-output name=type::bugfix"
        else
          echo "::set-output name=type::other"
        fi

    - name: Create badge
      id: create-badge
      run: |
        PR_TYPE=${{ steps.determine-pr-type.outputs.type }}
        BADGE_URL="https://img.shields.io/badge/PR-${PR_TYPE}-blue"
        echo "::set-output name=badge-url::$BADGE_URL"

    - name: Add badge to PR comment
      run: |
        BADGE_URL=${{ steps.create-badge.outputs.badge-url }}
        COMMENT="![PR Type Badge]($BADGE_URL)"
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -X POST -d "{\"body\": \"$COMMENT\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
